language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - git submodule update --force --init --recursive

script:
    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    # launch the tests
    # - sh ./runtests.sh

    # launch tutorial
    - if [ "$MATLAB_VER" == "R2016b" ]; then 
          sh ./tutorials/runtutorials.sh;
      fi;

after_success:
    - if [ "$MATLAB_VER" == "R2016b" ]; then
      bash <(curl -s https://codecov.io/bash) -f "!*.lst";
      export PATH="/var/lib/jenkins/.local/bin":$PATH;
      pip install --user -r docs/requirements.txt
      here=`pwd`;
      python ~/github_stats.py $here/docs/source/contributors.rst;
      python -c "from documenter.deploy import Documentation; doc = Documentation('github.com/opencobra/cobratoolbox', local_upstream='/var/lib/jenkins/workspace/COBRAToolbox-branches-auto-doc/MATLAB_VER/R2016b'); doc.deploy()";
      fi
