language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - git rm --cached binary
#    - git rm --cached external/SBMLToolbox
#    - git rm --cached external/lusol
#    - git rm --cached external/pdco
#    - git rm --cached external/Smith-Decomposition
    - git submodule update --force --init --recursive

script:
    - pwd
    - cd ~/COBRAmodels
    - git pull
    - cd -
    - sh ./runtests.sh

#deploy:

after_success:
    - if [ "$MATLAB_VER" == "R2016b" ]; then bash <(curl -s https://codecov.io/bash); fi
