name: testReport (Comment on PR)

on:
  workflow_run:
    workflows: ['cobratoolboxCI (merge, test, and upload)']
    types: [completed]
    
permissions:
  contents: write
  pull-requests: write

jobs:
  publish-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    
      - name: Download CTRF Artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          name: testReport
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Download PR Number Artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          name: pr_number
          run_id: ${{ github.event.workflow_run.id }}
          path: pr_number

      - name: Read PR Number
        id: read_pr_number
        run: |
          PR_NUMBER=$(cat pr_number/pr_number.txt)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.6
        with:
          report-path: 'artifacts/ctrf-report.json'          
          community-report: true
          community-report-name: 'cobra-report'
          issue: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
